-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

-- Type: plataformas

-- DROP TYPE IF EXISTS public.plataformas;

CREATE TYPE public.plataformas AS ENUM
    ('twitter', 'instagram', 'facebook', 'tiktok');

ALTER TYPE public.plataformas
    OWNER TO supabase_admin;

-- Type: tipo_eleicoes

-- DROP TYPE IF EXISTS public.tipo_eleicoes;

CREATE TYPE public.tipo_eleicoes AS ENUM
    ('gerais', 'estaduais', 'municipais');

-- Type: titulos

-- DROP TYPE IF EXISTS public.titulos;

CREATE TYPE public.titulos AS ENUM
    ('presidencia', 'vice-presidencia');

ALTER TYPE public.tipo_eleicoes
    OWNER TO supabase_admin;

CREATE TABLE IF NOT EXISTS public.eleicao
(
    eleicao_uid uuid NOT NULL DEFAULT uuid_generate_v4(),
    ano smallint NOT NULL,
    tipo tipo_eleicoes NOT NULL,
    CONSTRAINT eleicao_pkey PRIMARY KEY (eleicao_uid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.eleicao
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.eleicao TO postgres;

GRANT ALL ON TABLE public.eleicao TO supabase_admin;

GRANT ALL ON TABLE public.eleicao TO authenticated;

GRANT ALL ON TABLE public.eleicao TO service_role;

CREATE TABLE IF NOT EXISTS public.candidatura
(
    candidatura_uid uuid NOT NULL DEFAULT uuid_generate_v4(),
    candidato_uid uuid NOT NULL,
    eleicao_uid uuid NOT NULL,
    cargo_uid uuid NOT NULL,
    partido character varying COLLATE pg_catalog."default" NOT NULL,
    numero smallint NOT NULL,
    elegivel boolean NOT NULL DEFAULT true,
    confirmado boolean NOT NULL DEFAULT false,
    CONSTRAINT candidatura_pkey PRIMARY KEY (candidatura_uid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.candidatura
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.candidatura TO postgres;

GRANT ALL ON TABLE public.candidatura TO supabase_admin;

GRANT ALL ON TABLE public.candidatura TO authenticated;

GRANT ALL ON TABLE public.candidatura TO service_role;

CREATE TABLE IF NOT EXISTS public.cargo
(
    cargo_uid uuid NOT NULL DEFAULT uuid_generate_v4(),
    titulo titulos NOT NULL,
    CONSTRAINT cargo_pkey PRIMARY KEY (cargo_uid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.cargo
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.cargo TO postgres;

GRANT ALL ON TABLE public.cargo TO supabase_admin;

GRANT ALL ON TABLE public.cargo TO authenticated;

GRANT ALL ON TABLE public.cargo TO service_role;

CREATE TABLE IF NOT EXISTS public.rede_social
(
    rede_social_uid uuid NOT NULL DEFAULT uuid_generate_v4(),
    candidato_uid uuid NOT NULL,
    url character varying COLLATE pg_catalog."default" NOT NULL,
    plataforma plataformas NOT NULL,
    CONSTRAINT rede_social_pkey PRIMARY KEY (rede_social_uid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.rede_social
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.rede_social TO postgres;

GRANT ALL ON TABLE public.rede_social TO supabase_admin;

GRANT ALL ON TABLE public.rede_social TO authenticated;

GRANT ALL ON TABLE public.rede_social TO service_role;

CREATE TABLE IF NOT EXISTS public.candidato
(
    candidato_uid uuid NOT NULL DEFAULT uuid_generate_v4(),
    nome character varying COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default",
    CONSTRAINT candidato_pkey PRIMARY KEY (candidato_uid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.candidato
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.candidato TO postgres;

GRANT ALL ON TABLE public.candidato TO supabase_admin;

GRANT ALL ON TABLE public.candidato TO authenticated;

GRANT ALL ON TABLE public.candidato TO service_role;
