-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

-- Type: cargo_titulos

-- DROP TYPE IF EXISTS public.cargo_titulos;

CREATE TYPE public.cargo_titulos AS ENUM
    ('presidencia', 'vice-presidencia');

ALTER TYPE public.cargo_titulos
    OWNER TO postgres;

DROP TABLE IF EXISTS public.cargo CASCADE;

ALTER TABLE IF EXISTS public.candidatura DROP COLUMN IF EXISTS cargo_uid;

ALTER TABLE IF EXISTS public.candidatura DROP COLUMN IF EXISTS cargo;

ALTER TABLE public.candidatura ADD COLUMN cargo cargo_titulos;

ALTER TABLE IF EXISTS public.candidatura
    ADD CONSTRAINT candidatura_candidato_uid_fkey FOREIGN KEY (candidato_uid)
    REFERENCES public.candidato (candidato_uid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.candidatura
    ADD CONSTRAINT candidatura_eleicao_uid_fkey FOREIGN KEY (eleicao_uid)
    REFERENCES public.eleicao (eleicao_uid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.rede_social
    ADD CONSTRAINT rede_social_candidato_uid_fkey FOREIGN KEY (candidato_uid)
    REFERENCES public.candidato (candidato_uid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

DROP TYPE IF EXISTS public.titulos;
